Adicionando url glpi nova

diff --git a/pipelines/task-update-git.yaml b/pipelines/task-update-git.yaml
--- a/pipelines/task-update-git.yaml
+++ b/pipelines/task-update-git.yaml
@@ -42,12 +42,29 @@ spec:
         set -e
         git config --global user.email "tekton@example.com"
         git config --global user.name "Tekton Pipeline"
+        
         AUTH_URL=$(echo "$GIT_REPO_URL" | sed "s|https://|https://$USERNAME:$PASSWORD@|")
+        
         git clone "$AUTH_URL" repo
         cd repo
         git checkout "$GIT_REVISION"
         git pull "$AUTH_URL" "$GIT_REVISION"
+        
+        # Verifica se o arquivo existe
+        if [ ! -f "$FILE_PATH" ]; then
+          echo "ERROR: File $FILE_PATH not found!"
+          exit 1
+        fi
+        
+        # Faz a substituição
         sed -i "s/newTag: .*/newTag: $NEW_VALUE/" "$FILE_PATH"
+        
+        # Verifica se o sed realmente alterou algo
+        if git diff --quiet; then
+          echo "No changes detected in $FILE_PATH. Skipping commit."
+          exit 0
+        fi
+        
         git add "$FILE_PATH"
         git commit -m "ci: update image to $NEW_VALUE [skip ci]"
         git push "$AUTH_URL" "$GIT_REVISION"
